include: [".well-known"]
exclude: ["site.sublime-project","site.sublime-workspace"]
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
title: "Enrico Grillo"
url: "http://grillo.lighting"
twitter:
  username: redbassett
logo: "/images/identicon.png"
image: "/images/identicon.png"

